### ISSUE TITLE
有python的吗

### ISSUE THREAD

**Issue by wfcz10086** [lijiachang/spot_future_arbitrage#2]
我想要把一块  加入到https://github.com/wfcz10086/futures_ext 可以吗？

**Comment by lijiachang** [comment]
有，Python版本有完全体，可以生产运行的版本。
基于Django 4.2，其实只用到了Django orm管理数据库。

还没开源，不过有开源的打算。

**Comment by wfcz10086** [comment]
跑的数据怎么样？

**Comment by lijiachang** [comment]
不清楚，我帮小组写的，他们在跑，后续没关注。

**Comment by lijiachang** [comment]
@wfcz10086 https://github.com/lijiachang/okx_spot_future_arbitrage
